<?php

namespace Database\Seeders;

use DateTime;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MemoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('memos')->insert([
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'マイグレーションについて',
                'shortMemo' => 'マイグレーションについてすごくわかりやすくまとめられてます!',
                'type' => 0,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'user_id' => 2,
                'group_id' => 2,
                'title' => 'リュウジ式至高のレシピ',
                'shortMemo' => '初めての料理本におすすめです!!',
                'type' => 1,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'user_id' => 3,
                'group_id' => 3,
                'title' => 'プログラミングの教材として最もおすすめのサイト',
                'shortMemo' => 'プログラミングのことは、ほぼこのサイトで学びました!!',
                'type' => 0,
                'created_at' => new DateTime,
                'updated_at' => new DateTime,
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ１',
                'shortMemo' => 'メモ１の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-10 days'),
                'updated_at' => new DateTime('-10 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ２',
                'shortMemo' => 'メモ２の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-10 days'),
                'updated_at' => new DateTime('-10 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ３',
                'shortMemo' => 'メモ３の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-11 days'),
                'updated_at' => new DateTime('-11 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ４',
                'shortMemo' => 'メモ４の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-12 days'),
                'updated_at' => new DateTime('-12 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ５',
                'shortMemo' => 'メモ５の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-13 days'),
                'updated_at' => new DateTime('-13 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ６',
                'shortMemo' => 'メモ６の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-14 days'),
                'updated_at' => new DateTime('-14 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ７',
                'shortMemo' => 'メモ７の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-15 days'),
                'updated_at' => new DateTime('-15 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ８',
                'shortMemo' => 'メモ８の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-16 days'),
                'updated_at' => new DateTime('-16 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ９',
                'shortMemo' => 'メモ９の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-17 days'),
                'updated_at' => new DateTime('-17 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ10',
                'shortMemo' => 'メモ10の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-18 days'),
                'updated_at' => new DateTime('-18 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ11',
                'shortMemo' => 'メモ11の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-19 days'),
                'updated_at' => new DateTime('-19 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ12',
                'shortMemo' => 'メモ12の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-20 days'),
                'updated_at' => new DateTime('-20 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ13',
                'shortMemo' => 'メモ13の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-21 days'),
                'updated_at' => new DateTime('-21 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ14',
                'shortMemo' => 'メモ14の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-22 days'),
                'updated_at' => new DateTime('-22 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ15',
                'shortMemo' => 'メモ15の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-23 days'),
                'updated_at' => new DateTime('-23 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ16',
                'shortMemo' => 'メモ16の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-24 days'),
                'updated_at' => new DateTime('-24 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ17',
                'shortMemo' => 'メモ17の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-25 days'),
                'updated_at' => new DateTime('-25 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ18',
                'shortMemo' => 'メモ18の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-26 days'),
                'updated_at' => new DateTime('-26 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ19',
                'shortMemo' => 'メモ19の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-27 days'),
                'updated_at' => new DateTime('-27 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ20',
                'shortMemo' => 'メモ20の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-28 days'),
                'updated_at' => new DateTime('-28 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ21',
                'shortMemo' => 'メモ21の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-29 days'),
                'updated_at' => new DateTime('-29 days'),
            ],
            [
                'user_id' => 1,
                'group_id' => 1,
                'title' => 'メモ22',
                'shortMemo' => 'メモ22の内容です。',
                'type' => 1,
                'created_at' => new DateTime('-30 days'),
                'updated_at' => new DateTime('-30 days'),
            ],
        ]);
    }
}
