<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                'email' => 'test1@test.com',
                'password' => Hash::make('password0000001'),
                'nickname' => 'たろう',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'test2@test.com',
                'password' => Hash::make('password0000002'),
                'nickname' => 'はなこ',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'test3@test.com',
                'password' => Hash::make('password0000003'),
                'nickname' => '二郎さん',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'admin0@admin.com',
                'password' => Hash::make('password_admin0000000'),
                'nickname' => '運営トップ太郎',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'admin1@admin.com',
                'password' => Hash::make('password_admin0000001'),
                'nickname' => '運営太郎',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'admin2@admin.com',
                'password' => Hash::make('password_admin0000002'),
                'nickname' => 'うんえい子',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'admin88@admin.com',
                'password' => Hash::make('password_admin0000088'),
                'nickname' => '運営悪男',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'admin321@admin.com',
                'password' => Hash::make('password_admin0000321'),
                'nickname' => 'うんえい悪子',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'test333@test.com',
                'password' => Hash::make('password0000333'),
                'nickname' => 'テスト333',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user10@test.com',
                'password' => Hash::make('password0000010'),
                'nickname' => 'ユーザー10',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user11@test.com',
                'password' => Hash::make('password0000011'),
                'nickname' => 'ユーザー11',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user12@test.com',
                'password' => Hash::make('password0000012'),
                'nickname' => 'ユーザー12',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user13@test.com',
                'password' => Hash::make('password0000013'),
                'nickname' => 'ユーザー13',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user14@test.com',
                'password' => Hash::make('password0000014'),
                'nickname' => 'ユーザー14',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user15@test.com',
                'password' => Hash::make('password0000015'),
                'nickname' => 'ユーザー15',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user16@test.com',
                'password' => Hash::make('password0000016'),
                'nickname' => 'ユーザー16',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user17@test.com',
                'password' => Hash::make('password0000017'),
                'nickname' => 'ユーザー17',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user18@test.com',
                'password' => Hash::make('password0000018'),
                'nickname' => 'ユーザー18',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user19@test.com',
                'password' => Hash::make('password0000019'),
                'nickname' => 'ユーザー19',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user20@test.com',
                'password' => Hash::make('password0000020'),
                'nickname' => 'ユーザー20',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user21@test.com',
                'password' => Hash::make('password0000021'),
                'nickname' => 'ユーザー21',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user22@test.com',
                'password' => Hash::make('password0000022'),
                'nickname' => 'ユーザー22',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user23@test.com',
                'password' => Hash::make('password0000023'),
                'nickname' => 'ユーザー23',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user24@test.com',
                'password' => Hash::make('password0000024'),
                'nickname' => 'ユーザー24',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user25@test.com',
                'password' => Hash::make('password0000025'),
                'nickname' => 'ユーザー25',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user26@test.com',
                'password' => Hash::make('password0000026'),
                'nickname' => 'ユーザー26',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user27@test.com',
                'password' => Hash::make('password0000027'),
                'nickname' => 'ユーザー27',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user28@test.com',
                'password' => Hash::make('password0000028'),
                'nickname' => 'ユーザー28',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user29@test.com',
                'password' => Hash::make('password0000029'),
                'nickname' => 'ユーザー29',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user30@test.com',
                'password' => Hash::make('password0000030'),
                'nickname' => 'ユーザー30',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user31@test.com',
                'password' => Hash::make('admin_password0000031'),
                'nickname' => 'ユーザー31',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user32@test.com',
                'password' => Hash::make('admin_password0000032'),
                'nickname' => 'ユーザー32',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user33@test.com',
                'password' => Hash::make('admin_password0000033'),
                'nickname' => 'ユーザー33',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user34@test.com',
                'password' => Hash::make('admin_password0000034'),
                'nickname' => 'ユーザー34',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user35@test.com',
                'password' => Hash::make('admin_password0000035'),
                'nickname' => 'ユーザー35',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user36@test.com',
                'password' => Hash::make('admin_password0000036'),
                'nickname' => 'ユーザー36',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user37@test.com',
                'password' => Hash::make('admin_password0000037'),
                'nickname' => 'ユーザー37',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user38@test.com',
                'password' => Hash::make('admin_password0000038'),
                'nickname' => 'ユーザー38',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user39@test.com',
                'password' => Hash::make('admin_password0000039'),
                'nickname' => 'ユーザー39',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user40@test.com',
                'password' => Hash::make('admin_password0000040'),
                'nickname' => 'ユーザー40',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user41@test.com',
                'password' => Hash::make('admin_password0000041'),
                'nickname' => 'ユーザー41',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user42@test.com',
                'password' => Hash::make('admin_password0000042'),
                'nickname' => 'ユーザー42',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user43@test.com',
                'password' => Hash::make('admin_password0000043'),
                'nickname' => 'ユーザー43',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user44@test.com',
                'password' => Hash::make('admin_password0000044'),
                'nickname' => 'ユーザー44',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user45@test.com',
                'password' => Hash::make('admin_password0000045'),
                'nickname' => 'ユーザー45',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user46@test.com',
                'password' => Hash::make('admin_password0000046'),
                'nickname' => 'ユーザー46',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user47@test.com',
                'password' => Hash::make('admin_password0000047'),
                'nickname' => 'ユーザー47',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user48@test.com',
                'password' => Hash::make('admin_password0000048'),
                'nickname' => 'ユーザー48',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user49@test.com',
                'password' => Hash::make('admin_password0000049'),
                'nickname' => 'ユーザー49',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user50@test.com',
                'password' => Hash::make('admin_password0000050'),
                'nickname' => 'ユーザー50',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user51@test.com',
                'password' => Hash::make('password0000051'),
                'nickname' => 'ユーザー51',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user52@test.com',
                'password' => Hash::make('password0000052'),
                'nickname' => 'ユーザー52',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user53@test.com',
                'password' => Hash::make('password0000053'),
                'nickname' => 'ユーザー53',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user54@test.com',
                'password' => Hash::make('password0000054'),
                'nickname' => 'ユーザー54',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user55@test.com',
                'password' => Hash::make('password0000055'),
                'nickname' => 'ユーザー55',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user56@test.com',
                'password' => Hash::make('password0000056'),
                'nickname' => 'ユーザー56',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user57@test.com',
                'password' => Hash::make('password0000057'),
                'nickname' => 'ユーザー57',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user58@test.com',
                'password' => Hash::make('password0000058'),
                'nickname' => 'ユーザー58',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user59@test.com',
                'password' => Hash::make('password0000059'),
                'nickname' => 'ユーザー59',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user60@test.com',
                'password' => Hash::make('password0000060'),
                'nickname' => 'ユーザー60',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->insert([
                'email' => $user['email'],
                'password' => $user['password'],
                'nickname' => $user['nickname'],
                'suspension_state' => $user['suspension_state'],
                'username' => '@'.(string) Str::ulid(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
