<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                'email' => 'test1@test.com',
                'password' => Hash::make('password1'),
                'nickname' => 'たろう',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'test2@test.com',
                'password' => Hash::make('password2'),
                'nickname' => 'はなこ',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'test3@test.com',
                'password' => Hash::make('password3'),
                'nickname' => '二郎さん',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'admin0@admin.com',
                'password' => Hash::make('password_admin0'),
                'nickname' => '運営トップ太郎',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'admin1@admin.com',
                'password' => Hash::make('password_admin1'),
                'nickname' => '運営太郎',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'admin2@admin.com',
                'password' => Hash::make('password_admin2'),
                'nickname' => 'うんえい子',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'admin88@admin.com',
                'password' => Hash::make('password_admin88'),
                'nickname' => '運営悪男',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'admin321@admin.com',
                'password' => Hash::make('password_admin321'),
                'nickname' => 'うんえい悪子',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'test333@test.com',
                'password' => Hash::make('password333'),
                'nickname' => 'テスト333',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user10@test.com',
                'password' => Hash::make('password10'),
                'nickname' => 'ユーザー10',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user11@test.com',
                'password' => Hash::make('password11'),
                'nickname' => 'ユーザー11',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user12@test.com',
                'password' => Hash::make('password12'),
                'nickname' => 'ユーザー12',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user13@test.com',
                'password' => Hash::make('password13'),
                'nickname' => 'ユーザー13',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user14@test.com',
                'password' => Hash::make('password14'),
                'nickname' => 'ユーザー14',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user15@test.com',
                'password' => Hash::make('password15'),
                'nickname' => 'ユーザー15',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user16@test.com',
                'password' => Hash::make('password16'),
                'nickname' => 'ユーザー16',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user17@test.com',
                'password' => Hash::make('password17'),
                'nickname' => 'ユーザー17',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user18@test.com',
                'password' => Hash::make('password18'),
                'nickname' => 'ユーザー18',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user19@test.com',
                'password' => Hash::make('password19'),
                'nickname' => 'ユーザー19',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user20@test.com',
                'password' => Hash::make('password20'),
                'nickname' => 'ユーザー20',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user21@test.com',
                'password' => Hash::make('password21'),
                'nickname' => 'ユーザー21',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user22@test.com',
                'password' => Hash::make('password22'),
                'nickname' => 'ユーザー22',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user23@test.com',
                'password' => Hash::make('password23'),
                'nickname' => 'ユーザー23',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user24@test.com',
                'password' => Hash::make('password24'),
                'nickname' => 'ユーザー24',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user25@test.com',
                'password' => Hash::make('password25'),
                'nickname' => 'ユーザー25',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user26@test.com',
                'password' => Hash::make('password26'),
                'nickname' => 'ユーザー26',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user27@test.com',
                'password' => Hash::make('password27'),
                'nickname' => 'ユーザー27',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user28@test.com',
                'password' => Hash::make('password28'),
                'nickname' => 'ユーザー28',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user29@test.com',
                'password' => Hash::make('password29'),
                'nickname' => 'ユーザー29',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user30@test.com',
                'password' => Hash::make('password30'),
                'nickname' => 'ユーザー30',
                'suspension_state' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user31@test.com',
                'password' => Hash::make('admin_password31'),
                'nickname' => 'ユーザー31',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user32@test.com',
                'password' => Hash::make('admin_password32'),
                'nickname' => 'ユーザー32',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user33@test.com',
                'password' => Hash::make('admin_password33'),
                'nickname' => 'ユーザー33',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user34@test.com',
                'password' => Hash::make('admin_password34'),
                'nickname' => 'ユーザー34',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user35@test.com',
                'password' => Hash::make('admin_password35'),
                'nickname' => 'ユーザー35',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user36@test.com',
                'password' => Hash::make('admin_password36'),
                'nickname' => 'ユーザー36',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user37@test.com',
                'password' => Hash::make('admin_password37'),
                'nickname' => 'ユーザー37',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user38@test.com',
                'password' => Hash::make('admin_password38'),
                'nickname' => 'ユーザー38',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user39@test.com',
                'password' => Hash::make('admin_password39'),
                'nickname' => 'ユーザー39',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user40@test.com',
                'password' => Hash::make('admin_password40'),
                'nickname' => 'ユーザー40',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user41@test.com',
                'password' => Hash::make('admin_password41'),
                'nickname' => 'ユーザー41',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user42@test.com',
                'password' => Hash::make('admin_password42'),
                'nickname' => 'ユーザー42',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user43@test.com',
                'password' => Hash::make('admin_password43'),
                'nickname' => 'ユーザー43',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user44@test.com',
                'password' => Hash::make('admin_password44'),
                'nickname' => 'ユーザー44',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user45@test.com',
                'password' => Hash::make('admin_password45'),
                'nickname' => 'ユーザー45',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user46@test.com',
                'password' => Hash::make('admin_password46'),
                'nickname' => 'ユーザー46',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user47@test.com',
                'password' => Hash::make('admin_password47'),
                'nickname' => 'ユーザー47',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user48@test.com',
                'password' => Hash::make('admin_password48'),
                'nickname' => 'ユーザー48',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user49@test.com',
                'password' => Hash::make('admin_password49'),
                'nickname' => 'ユーザー49',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user50@test.com',
                'password' => Hash::make('admin_password50'),
                'nickname' => 'ユーザー50',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user51@test.com',
                'password' => Hash::make('password51'),
                'nickname' => 'ユーザー51',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user52@test.com',
                'password' => Hash::make('password52'),
                'nickname' => 'ユーザー52',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user53@test.com',
                'password' => Hash::make('password53'),
                'nickname' => 'ユーザー53',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user54@test.com',
                'password' => Hash::make('password54'),
                'nickname' => 'ユーザー54',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user55@test.com',
                'password' => Hash::make('password55'),
                'nickname' => 'ユーザー55',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user56@test.com',
                'password' => Hash::make('password56'),
                'nickname' => 'ユーザー56',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user57@test.com',
                'password' => Hash::make('password57'),
                'nickname' => 'ユーザー57',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user58@test.com',
                'password' => Hash::make('password58'),
                'nickname' => 'ユーザー58',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user59@test.com',
                'password' => Hash::make('password59'),
                'nickname' => 'ユーザー59',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'email' => 'user60@test.com',
                'password' => Hash::make('password60'),
                'nickname' => 'ユーザー60',
                'suspension_state' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->insert([
                'email' => $user['email'],
                'password' => $user['password'],
                'nickname' => $user['nickname'],
                'suspension_state' => $user['suspension_state'],
                'username' => '@' . (string) Str::ulid(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
